sudo: required
services:
  - docker
language: java
jdk:
  - oraclejdk8
  - openjdk8
script:
  - set -e
  - docker info
  - docker --help
  - dockerd --help
  - docker pull hello-world #for some IT cases
  - docker pull ubuntu # for container IT cases
  - docker run -d --privileged -p 12375:2375 docker:dind
  - mvn clean install -Pitcases jacoco:report coveralls:report
