sudo: required
services:
  - docker
language: java
jdk:
  - oraclejdk8
  - openjdk8
script:
  - set -e
  - docker pull hello-world #for some IT cases
  - mvn clean install -Pcheckstyle,itcases jacoco:report coveralls:report
