sudo: required
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
#services:
#  - docker
language: java
jdk:
  - openjdk8
script:
  - set -e
  - docker info
  - docker --help
  - dockerd --help
  - docker pull hello-world #for some IT cases
  - docker pull ubuntu # for container IT cases
  - docker run -d --privileged -p 12375:2375 docker:dind
  - mvn clean install -Pcheckstyle,itcases -PtestCoverage jacoco:report coveralls:report
